  
language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: "${AWS_ACCESS_KEY_ID}"
  secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
  bucket: "${DEPLOY_BUCKET}"
  local_dir: build
  keep-history: true
  on:
    branch: master
before_script:
  - "npm i"
script:
  - "npm run build"
after_deploy:
  - "echo Successfully Deployed Site"
